# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: bush...
      run: wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
    - name: chmod...
      run: chmod +x ./dotnet-install.sh
    - name: start
      run: ./dotnet-install.sh --version latest --runtime aspnetcore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: install
      run: bash <(curl -sSL https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/docker/install.sh)
    - name: Test
      run: dotnet ./Ray.BiliBiliTool.Console.dll --runTasks=Login
