name: BiliBiliTool Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tool:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    # 仅需下载预编译版本（删除源码构建步骤）
    - name: Download and extract BiliBiliTool
      run: |
        wget -q https://github.com/RayWangQvQ/BiliBiliToolPro/releases/download/0.3.1/bilibili-tool-pro-v0.3.1-linux-x64.zip
        unzip -q bilibili-tool-pro-v0.3.1-linux-x64.zip -d bili-tool
        
    # 添加执行权限并运行
    - name: Run BiliBiliTool
      run: |
        cd bili-tool/linux-x64
        chmod +x Ray.BiliBiliTool.Console
        ./Ray.BiliBiliTool.Console --runTasks=Login
        ./Ray.BiliBiliTool.Console
